In [ ]:
#Name:M.Praveenraj
#Regno:230701396
#CS23334-Fundamentals of DataScience
import numpy as np
array=np.random.randint(1,100,9)
array




array([17, 73, 17, 43, 86, 37, 31, 88, 76])

In [9]:
np.sqrt(array)

array([4.12310563, 8.54400375, 4.12310563, 6.55743852, 9.2736185 ,
       6.08276253, 5.56776436, 9.38083152, 8.71779789])

In [11]:
array.ndim

1

In [12]:
new_array=array.reshape(3,3)
new_array


array([[17, 73, 17],
       [43, 86, 37],
       [31, 88, 76]])

In [14]:
new_array.ndim

2

In [16]:
new_array.ravel()

array([17, 73, 17, 43, 86, 37, 31, 88, 76])

In [18]:
newm=new_array.reshape(3,3)


In [20]:
newm

array([[17, 73, 17],
       [43, 86, 37],
       [31, 88, 76]])

In [22]:
newm[2,1:3]

array([88, 76])

In [24]:
newm[1:2,1:3]

array([[86, 37]])

In [26]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int64)

In [28]:
new_array[0:2,0:1]

array([[17],
       [43]])

In [30]:
new_array[0:3,0:1]


array([[17],
       [43],
       [31]])

In [31]:
new_array[1:3]


array([[43, 86, 37],
       [31, 88, 76]])